/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;
import Clases.Programa;
import Clases.Servicio;
import Metodos.Mprograma;
import Metodos.Mservicio;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Mayra Garrido
 */
public class Becados extends javax.swing.JPanel {

    /**
     * Creates new form Becados
     */
    Mprograma pro = new Mprograma();
    Programa prog ;
    Mservicio ser = new Mservicio();
    Servicio servi;
    public Becados() {
        initComponents();
        pro.consulta(JCBprograma);
        ser.consulta(JCBservicio);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBguardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JCBnombre = new javax.swing.JComboBox<>();
        JBeditar = new javax.swing.JButton();
        TFnombre = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jYearChooser3 = new com.toedter.calendar.JYearChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jYearChooser4 = new com.toedter.calendar.JYearChooser();
        jLabel28 = new javax.swing.JLabel();
        jYearChooser5 = new com.toedter.calendar.JYearChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        JCBprograma = new javax.swing.JComboBox<>();
        JCBservicio = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        JTruta = new javax.swing.JTextField();
        JBsubirfoto = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBguardar.setText("GUARDAR");
        add(JBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, -1, -1));

        jButton1.setText("NUEVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBeditar.setText("EDITAR");
        JBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(JCBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(JBeditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(JCBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBeditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        TFnombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(TFnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, -1));

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, -1));

        jTextField2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 180, -1));

        jTextField3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 200, -1));

        jTextField4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 320, 80));

        jTextField5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 190, -1));

        jTextField8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 250, -1));

        jTextField9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 190, -1));

        jTextField10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 240, -1));

        jTextField11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 240, -1));

        jTextField12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 250, -1));

        jTextField13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 260, -1));

        jTextField14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 290, 60));

        jTextField15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 200, -1));

        jTextField17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 190, -1));

        jTextField18.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 260, -1));

        jTextField19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 260, -1));

        jTextField20.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, -1));

        jTextField21.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 370, 70));

        jTextField31.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField31.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField31.setDoubleBuffered(true);
        jTextField31.setDragEnabled(true);
        add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 330, 60));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Apellodo paterno");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 120, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Apellido materno");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 150, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de nacimiento");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Lugar de nacimiento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Dirección permanente");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Dirección actual");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel8.setText("foto");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 120, 140));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Teléfono celular");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Correo");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setText("Nombre del padre");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setText("Nombre de la madre");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setText("Lugar que ocupa en la familia");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setText("Trabajo actual");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setText("Año de gradución  de villa (bachillerato)");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setText("Año de entrada a villa");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setText("Año de graduacion de villa (Secundaria)");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel18.setText("Numero de hermanos totales");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));
        add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 200, -1));
        add(jYearChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 240, -1));
        add(jYearChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 250, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel19.setText("Facebook");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel20.setText("Instagram");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel21.setText("Otra red social");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setText("Carrera");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel23.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel23.setText("Universidad");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel24.setText("Dirección de la universidad");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel25.setText("Duración en años de la carrera");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel26.setText("Sistema de estudio ");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel27.setText("Año de inicio en la beca");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));
        add(jYearChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 140, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel28.setText("Año de graduación");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));
        add(jYearChooser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 130, -1));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 160, -1));
        add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 240, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel29.setText("Fecha de baja en la beca");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, -1, -1));

        jLabel30.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel30.setText("Logros recibidos");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel31.setText("Estatus");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Graduado", "Baja" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, 150, -1));

        add(JCBprograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 220, -1));

        JCBservicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(JCBservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, 230, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel32.setText("Programa de beca");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, -1, -1));

        jLabel33.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel33.setText("Sitio del servicio");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bimestral", "Trimestral", "Cuatrimestral", "Semestral" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 150, -1));
        add(JTruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 200, -1));

        JBsubirfoto.setText("Subir foto");
        JBsubirfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsubirfotoActionPerformed(evt);
            }
        });
        add(JBsubirfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBeditarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void JBsubirfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsubirfotoActionPerformed
        // TODO add your handling code here:
       String carp="Documetos";
        File r = new File(carp);
          
                if(r.mkdir()){
                    System.out.println(r.getAbsolutePath());
                    System.out.println("carpeta creada");
                    
                }else{
                    System.out.println("carpeta no creada ya existe");
                }
        
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG % JPNG","jpg","png","jpng");
        j.setFileFilter(fil);
        
        int s = j.showOpenDialog(this);
        if(s == JFileChooser.APPROVE_OPTION){
            String ruta = j.getSelectedFile().getAbsolutePath();
            
            
            File archivo = new File(ruta);
            System.out.println(archivo.getAbsolutePath());
            archivo.renameTo(new File (r.getAbsolutePath()+File.separatorChar+archivo.getName()));
            System.out.println(r.getAbsolutePath()+archivo.getName());
            JTruta.setText(r.getAbsolutePath()+archivo.getName());
            
            
            
        }
        
        
        
    }//GEN-LAST:event_JBsubirfotoActionPerformed
public boolean moveFile(String fromFile, String toFile) {
    File origin = new File(fromFile);
    File destination = new File(toFile);
    if (origin.exists()) {
        try {
            InputStream in = new FileInputStream(origin);
            OutputStream out = new FileOutputStream(destination);
            byte[] buf = new byte[1024];
            int len;
            while ((len = in.read(buf)) > 0) {
                out.write(buf, 0, len);
            }
            in.close();
            out.close();
            return origin.delete();
        } catch (IOException ioe) {
            ioe.printStackTrace();
            return false;
        }
    } else {
        return false;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBeditar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBsubirfoto;
    private javax.swing.JComboBox<String> JCBnombre;
    private javax.swing.JComboBox<String> JCBprograma;
    private javax.swing.JComboBox<String> JCBservicio;
    private javax.swing.JTextField JTruta;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    private com.toedter.calendar.JYearChooser jYearChooser3;
    private com.toedter.calendar.JYearChooser jYearChooser4;
    private com.toedter.calendar.JYearChooser jYearChooser5;
    // End of variables declaration//GEN-END:variables
}
